server:
  port: 8282

spring:
  security:
    user:
      name: jdw
      password: jdw
  datasource:
    url: jdbc:mysql://localhost:3306/mylocaldb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

